### ISSUE TITLE
插件仓库无法连接更新列表

### ISSUE THREAD

**Issue by WROIATE** [garypang13/Actions-OpenWrt-Nginx#100]
我尝试了移动，电信直连无法连接，使用手机梯子访问https://op.supes.top:88/x64 也无法连接，都显示timeout，想知道是不是我哪操作有问题

**Comment by garypang13** [comment]
不好意思,是我这边DDNS问题,已经恢复了.

**Comment by WROIATE** [comment]
ok，了解

**Comment by WROIATE** [comment]
不过好像又挂了。。。
