### ISSUE TITLE
关于openclash工作不正常的问题

### ISSUE THREAD

**Issue by BirtyAs** [garypang13/Actions-OpenWrt-Nginx#113]
点击启动openclash 进入 第五步 的时候 就无反应了 系统进程显示正在执行 openclash restart CPU占用：0%  等了很久都这样   在其他固件中就不存在这个问题 （openclash为同一版本）
只有正确配置后点击启动openclash 重启系统后才能使用openclash 如果再此之后重启openclash 还是会和上段一样。

**Comment by garypang13** [comment]
openclash运行没问题的,有不少人在用,我自己也测试过两次,注意是否有clash主程序,安装完后重启下.

**Comment by lx521603** [comment]
我的是最近几天的passwall，ssr+都编译不进固件。可以在线安装，有出错信息，有个仓库访问不了。但能安装成功。不过passwall会有问题。就是用一段时间，国外网站访问不了，把adh，smartdns都关了，用8.8.8.8，还是访问不了。
ssr没试。
