### ISSUE TITLE
DDNS 阿里云不能启用？

### ISSUE THREAD

**Issue by qinkangdeid** [garypang13/Actions-OpenWrt-Nginx#13]
正常的配置动态DDNS的时候失败了 点启用一直都不成功 0419的固件
![image](https://user-images.githubusercontent.com/17582522/79679463-ca2dcc80-8238-11ea-8e67-f914384dffec.png)
![image](https://user-images.githubusercontent.com/17582522/79679468-da45ac00-8238-11ea-8ede-28eb7ef46ede.png)

**Comment by qinkangdeid** [comment]
大神 域名的填写不能是通配符*吗？ 我设置一个固定的就可以了 但是，。。。。。。。要通配符怎么设置？其他的固件都是填写*就可以了  
![image](https://user-images.githubusercontent.com/17582522/79679657-4f65b100-823a-11ea-9ac6-48b8770c2878.png)

**Comment by garypang13** [comment]
通配符你要去阿里云域名解析里设置泛解析,
![a2020-4-19 13-21-10](https://user-images.githubusercontent.com/48883331/79680290-b0908300-8240-11ea-92ec-366801f9efbf.png)
