### ISSUE TITLE
老大，最近云编译都不成功

### ISSUE THREAD

**Issue by lx521603** [garypang13/Actions-OpenWrt-Nginx#14]
都是在Organize files这一步上。

每次都是不成功，然后删除仓库，全新fork还是失败，git pull到本地，git reset --hard到一个星期前的某个版本，又都是成功的。

望解决，谢谢

**Comment by garypang13** [comment]
不好意思,打包的时候找不到对应的文件导致的,应该修复了,更新build-openwrt.yml再试试.

**Comment by lx521603** [comment]
现在的问题是，编译成功了，但还有11个错误。

结果是releases里面只有source code的2个压缩文件，没有固件。

去actions里面也没找到firmware文件。

按照道理，即使不设置token，不生成releases，在actions里也是会有firmware文件的。

**Comment by garypang13** [comment]
actions里面也没找到firmware是因为 Upload firmware directory这步被跳过了,已修复.

**Comment by lx521603** [comment]
感谢，现在没问题了。但还有个插件的问题。

前几天看见你的更新百度网盘的插件说修复了，我想试试看（之前别人的固件里有这个插件，但登陆不了），就编译进去了。但我没发现固件里面有这个插件。
我以为没成功。

然后我去你的releases里，下载了luci-app-baidupcs-web.zip这个包，把包里的2个文件都上传，安装了。但界面里没有相关选项。

我到启动项里，看见baidupcs-web是启动了的。

**Comment by garypang13** [comment]
是因为你把NAS这个选项里的其他插件都去掉了导致的,
在 /usr/lib/lua/luci/controller/baidupcs-web.lua 第六行下添加
entry({"admin", "nas"}, firstchild(), "NAS", 45).dependent = false
即可.重启生效.

**Comment by lx521603** [comment]
感谢
