### ISSUE TITLE
transmission因为没有配置文件无法正常运行

### ISSUE THREAD

**Issue by doushang** [garypang13/Actions-OpenWrt-Nginx#15]
手动上传一份transmission的配置文件才能够正常运行，或者命令行运行service transmission restart也可以解决，但是luci界面重启无效

**Comment by garypang13** [comment]
默认没有/etc/config/transmission文件吗? 我没在用transmission没测试.
我看官方源码中默认是有配置文件的. 
https://github.com/openwrt/packages/blob/master/net/transmission/files/transmission.config
如果命令行能启动,但是通过luci界面不行那肯定不是没有配置文件造成的.

**Comment by doushang** [comment]
我可能初步找到了原因，tr默认的配置目录指向/tmp/transmission，但/tmp里没有transmission，新建一个然后重启transmission服务就好了
