### ISSUE TITLE
怎么修改默认登陆地址

### ISSUE THREAD

**Issue by assasec** [garypang13/Actions-OpenWrt-Nginx#17]
哪里修改默认登陆10.0.0.1

**Comment by garypang13** [comment]
https://github.com/garypang13/Actions-OpenWrt-Nginx/blob/master/diy/feeds/custom/luci/default-settings/files/zzz-default-settings
修改 uci set network.lan.ipaddr="10.0.0.1"

**Comment by doushang** [comment]
如果已经刷机，也可以控制台输入以下命令修改：
uci set network.lan.ipaddr=192.168.0.1
uci commit
/etc/init.d/network restart
