### ISSUE TITLE
SSH登入不进去,Turbo ACC DNS加速开不了

### ISSUE THREAD

**Issue by sorasoras** [garypang13/Actions-OpenWrt-Nginx#20]
1.SSH登入失败 提示 server refused to allocate pty 
2. Turbo ACC的DNS加速没法开 是跟什么插件冲突了？

谢了

**Comment by garypang13** [comment]
ssh登入失败我还没遇到过,不好排查.
Turbo ACC的DNS加速要重启后才生效

**Comment by sorasoras** [comment]
哦没事了 重启了都好了（
