### ISSUE TITLE
zzz-default-settings

### ISSUE THREAD

**Issue by hong0980** [garypang13/Actions-OpenWrt-Nginx#23]
在固件的zzz-default-settings文件打开来pppoe的密码和用户名还是都能看到，应该把它加密。

**Comment by garypang13** [comment]
编译好的固件的zzz-default-settings文件没办法查看的吧,如果担心泄露的话可以将仓库设为私密.

**Comment by hong0980** [comment]
能用7z打开固件的在etc/uci-defaults/99-zzz-default-settings里

**Comment by garypang13** [comment]
我用Bandizip和装载镜像都无法打开固件,
总之不要在公共传播的固件中包含任何个人隐私信息.

**Comment by ZeaKyX** [comment]
@garypang13   像题主说的这个目录，可以看到密码如下：
![image](https://user-images.githubusercontent.com/43315078/94386578-9b6a3980-017a-11eb-8d97-388acc67db69.png)
因为是Linux文件系统，所以在Linux环境下装载或解包都是极为简单的
至于` 如果担心泄露的话可以将仓库设为私密`，GitHub Action 对私有仓库有空间限制，新人基本不会选择
**希望大佬在readme中说明以上安全信息**，我看到好像很多人中招了。。。

**Comment by garypang13** [comment]
感谢提醒,已添加说明.
