### ISSUE TITLE
docker不能选中编译

### ISSUE THREAD

**Issue by lexin8** [garypang13/Actions-OpenWrt-Nginx#27]
make menuconfig里面有两个同样的luci-app-dockerman选项
只能选中子选项Include ttyd 编译出来没有Docker-CE不能运行
选中Include Docker-CE的话luci-app-dockerman就会消失，编译出来也没有docker

**Comment by garypang13** [comment]
把 CONFIG_IPV6=n 去掉

**Comment by lexin8** [comment]
感谢大佬回复！
[config.txt](https://github.com/garypang13/Actions-OpenWrt-Nginx/files/4567223/config.txt)
.config文件默认就是 # CONFIG_IPV6 is not set

**Comment by garypang13** [comment]
改为 CONFIG_IPV6=y
