### ISSUE TITLE
关于不编译nginx

### ISSUE THREAD

**Issue by ZiPenOk** [garypang13/Actions-OpenWrt-Nginx#28]
我只是用来做软路由,没有做站的想法,,
所以,我把nginx取消编译,把uhttp勾选上了,但变异完,无法访问luci

You don't have permission to access /cgi-bin/luci/ on this server

还有哪里需要设置吗

**Comment by garypang13** [comment]
加上 CONFIG_PACKAGE_luci=y

**Comment by ZiPenOk** [comment]
谢谢,再去试试
