### ISSUE TITLE
如何加入opentomcat主题?

### ISSUE THREAD

**Issue by ZiPenOk** [garypang13/Actions-OpenWrt-Nginx#30]
如何加入opentomcat主题?
默认的agon主题在部分界面显示异常
如何修改默认主题显示?
还有,切换darkmatter主题后,luci登录进去后就一片空白了,没显示

**Comment by garypang13** [comment]
opentomcat 不支持 luci 19.07
darkmatter空白的话应该也是不支持19.07,下版会去掉

在后台设置好主题,就是默认主题,系统升级不会影响主题设置
