### ISSUE TITLE
当我用pip3安装docker-compose时的问题

### ISSUE THREAD

**Issue by yangxiangguo** [garypang13/Actions-OpenWrt-Nginx#35]
pip3 install docker-compose 提示让我安装gcc
安装完gcc后，再次运行出现：
gcc: error: unrecognized command line option '-ffile-prefix-map=/home/XXX/bin/openwrt/build_dir/target-x86_64_musl/Python-3.8.2=Python-3.8.2'
而其中的XXX是我在谷歌云编译的时候的用户根目录，编译镜像的时候带进去了？我openwrt这个镜像跟XXX没任何关系的     怀疑是这个导致gcc不能用

**Comment by garypang13** [comment]
![dc](https://user-images.githubusercontent.com/48883331/81772464-8321b700-9518-11ea-9fce-ba953e996ac7.png)

我在我openwrt上测试了可以正常安装的,不过只能装 docker-compose 1.23.2这个版本

**Comment by yangxiangguo** [comment]
1.23.2确实能安装。。。。汗~
