### ISSUE TITLE
能不能加上注解

### ISSUE THREAD

**Issue by hong0980** [garypang13/Actions-OpenWrt-Nginx#36]
在脚本中能不能加上注解，有的命令看不懂要是加上注解就能学习下大佬的东西！还有[https://www.right.com.cn/forum/thread-928319-1-1.html](url)里有几个管控能不能提出来加进去，有几个还是很实用的。谢谢！

**Comment by garypang13** [comment]
好的,后续会加上注释
那几个管控插件没有开源,提出来有点麻烦,也没测试具体效果怎么样,等以后有时间的话再弄.

**Comment by yangxiangguo** [comment]
想要helloworld

**Comment by garypang13** [comment]
helloworld与ssr plus有冲突,暂时无法解决. 
https://github.com/jerrykuku/luci-app-vssr/issues/31#issuecomment-625567358
