### ISSUE TITLE
修改 10.0.0.1 为 192.168.1.1,和WAN顺序

### ISSUE THREAD

**Issue by QingHui653** [garypang13/Actions-OpenWrt-Nginx#38]
请问 ,能否将 10.0.0.1 和WAN LAN的顺序也设置为可配置项. 或者能否告知下 fork后如果修改吗?

**Comment by garypang13** [comment]
在 default-settings文件中 中修改.
uci set network.lan.ipaddr="10.0.0.1"
uci set network.lan.ifname="eth0"
uci set network.lan.ifname="eth1"
uci commit network

**Comment by QingHui653** [comment]
谢谢
