### ISSUE TITLE
希望能在 X86_64.config中加入多拨 和 koolProxyPlus 的配置

### ISSUE THREAD

**Issue by QingHui653** [garypang13/Actions-OpenWrt-Nginx#43]
如题

**Comment by garypang13** [comment]
多拨有提供单独的luci-app-syncdial.zip
 多拨需要的人真的不多,符合条件的宽带很少了,能多拨也不稳定,现在大部分人带宽都有几百兆,没必要去折腾那个,
koolProxyPlus 无法过滤https网站,现在网站基本都是https了,
