### ISSUE TITLE
ttydy以及winscp登录不进系统

### ISSUE THREAD

**Issue by ledewrt** [garypang13/Actions-OpenWrt-Nginx#47]
bug如题，winscp也连接不上，ttyd提示root用户不存在。

**Comment by garypang13** [comment]
通过浏览器能登录root后台吗

**Comment by ledewrt** [comment]
不能

**Comment by garypang13** [comment]
这个情况我还没遇到过,应该是特例,不保留数据重刷一次试试.

**Comment by ledewrt** [comment]
没有保留数据，刷完还重置了，也不行。后台网页端进不去，winscp直接提示拒接链接。

**Comment by garypang13** [comment]
是直接用的我编译好的固件吗?后台网页端进不去是打不开后台吗,那要么是没有相关的网卡驱动,要么就是网线接口差错了,

**Comment by ledewrt** [comment]
是后台网页端的ttyd终端服务进不去，系统后台能进去。

**Comment by garypang13** [comment]
是不是有安装OpenSSH,卸载了试试.
