### ISSUE TITLE
netdata 和 ttyd都不对啊

### ISSUE THREAD

**Issue by doumeki** [garypang13/Actions-OpenWrt-Nginx#48]
先感谢大佬在Lean隔壁回答我关于https的问题。

用了你的release 05.20-openwrt-x86-64-generic-squashfs-combined.img.gz
既没有ttyd, netdata也同样不支持https
是要重新照着你的编译吗？

**Comment by garypang13** [comment]
ttyd在服务里 名字叫终端

在 /etc/netdata/netdata.conf 文件末尾加上

[web]
    ssl key = 证书key地址
    ssl certificate = 证书cer地址
	tls version = 1.3
    tls ciphers = TLS13-AES-128-GCM-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH

**Comment by doumeki** [comment]
大概试了下，除和ttdy界面显示能出来但打不了字，其它都是好的。 
感谢

**Comment by garypang13** [comment]
我的ttyd一切正常,chrome浏览器
