### ISSUE TITLE
求请默认插件加入 Softether VPN ~

### ISSUE THREAD

**Issue by Tiexcn** [garypang13/Actions-OpenWrt-Nginx#5]
刷过这个版本 觉得超好用，界面反应超快，不过有一个小问题，开启AdguardHome 功能，会导致CPU满载，及网路出现赌赛，CPU G4400 ,应该足够跑了，不过这可能只是我的个例，不用管。

加入Softether VPN 基本感觉 就足够我用了。不用自己折腾编译。。。了。。3Q

**Comment by garypang13** [comment]
好的,后续如果还有其他人也需要的话就加上,Adguardhome满载的问题刷今天最新版试试,应该能解决.

**Comment by Tiexcn** [comment]
3Q.

**Comment by garypang13** [comment]
Softether VPN 暂时以独立插件的形式提供,可自行安装

**Comment by Tiexcn** [comment]
OK 已经用上了，3Q
