### ISSUE TITLE
分区大小设置问题.

### ISSUE THREAD

**Issue by QingHui653** [garypang13/Actions-OpenWrt-Nginx#58]
我想问下 我 应该怎么 在 config中设置分区大小. 我编译出来的固件 只有 512k,导致我这边修改配置无法完成写入操作. 谢谢
![image](https://user-images.githubusercontent.com/15207108/83318935-29d1bb80-a26c-11ea-95c9-2f26ad422fb0.png)

**Comment by garypang13** [comment]
CONFIG_TARGET_ROOTFS_PARTSIZE=960

**Comment by QingHui653** [comment]
谢谢
