### ISSUE TITLE
手机端今日头条APP问题

### ISSUE THREAD

**Issue by Ginua8292** [garypang13/Actions-OpenWrt-Nginx#59]
为什么手机端APP今日头条几率会连不上网络，无论怎么设置网络，只有把DNS改回营运商的DNS或者114类的公共DNS就可以！忘了说我是用爱快虚拟机运行固件当旁路由，挺喜欢这固件的！

**Comment by garypang13** [comment]
有使用adguardhome吗,可能是adguardhome的过滤规则屏蔽了某个域名,你可以自己排查下,然后加入白名单,我没在用头条系的APP.

**Comment by Ginua8292** [comment]
可以确认是adguardhome的问题，无论是关掉过滤规则还是不关都不行，只有把adguardhome关了才行！

**Comment by garypang13** [comment]
adguardhome本身应该不会有问题的,最可能还是规则的问题,有缓存的原因不一定关了规则马上就生效的.
