### ISSUE TITLE
default-settings内容如何调用加载配置。

### ISSUE THREAD

**Issue by jarod360** [garypang13/Actions-OpenWrt-Nginx#61]
老大您好。感谢您提供了优秀的项目。我现在使用其他人的云编译，想问下。default-settings里的设置内容，如何才能调用执行，需要在DIY.SH还是编译文件里执行。执行调用的命令如何写。不好意思因为用不到night 习惯了使用lede的固件。

**Comment by garypang13** [comment]
在diy.sh https://github.com/garypang13/Actions-OpenWrt-Nginx/blob/1417aca7c929e47560a9d4ed15372805cbd96b9a/diy.sh#L108

**Comment by jarod360** [comment]
好的，非常感谢大佬指点。
