### ISSUE TITLE
请问怎么开启IPV6

### ISSUE THREAD

**Issue by mh349990635** [garypang13/Actions-OpenWrt-Nginx#66]
请问怎么开启IPV6

**Comment by garypang13** [comment]
.config 中 CONFIG_IPV6=y

**Comment by mh349990635** [comment]
不好意思 我是下载编译好的img

**Comment by allgreenL** [comment]
我试了改 .config 中 CONFIG_IPV6=y 后WAN6口并不能连上ipv6，同样的机器上lean的版本可以。

**Comment by garypang13** [comment]
> 我试了改 .config 中 CONFIG_IPV6=y 后WAN6口并不能连上ipv6，同样的机器上lean的版本可以。

IPV6我并没有测试
 /etc/sysctl.d/99-custom.conf中
net.ipv6.conf.lo.disable_ipv6=1
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
去掉试试

**Comment by garypang13** [comment]
> 不好意思 我是下载编译好的img

编译好的img默认不包含IPV6.

**Comment by garypang13** [comment]
固件已开启IPV6支持.

**Comment by whao123yahoo** [comment]
> 固件已开启IPV6支持.

怎么配置呢？请教下。我看网上的教程都没有这个固件的😌
