### ISSUE TITLE
guest-wifi

### ISSUE THREAD

**Issue by 4041110** [garypang13/Actions-OpenWrt-Nginx#69]
你好。开启guest-wifi后编译好进路由后台提升这个
usr/lib/lua/luci/controller/guest-wifi.lua:5: attempt to call field 'loadc' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/guest-wifi.lua:5: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:1201: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:694: in function 'menu_json'
	/usr/lib/lua/luci/dispatcher.lua:795: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>

**Comment by garypang13** [comment]
@4041110 把 /usr/lib/lua/luci/controller/guest-wifi.lua 第五行的 luci.i18n.loadc("guest-wifi") 删掉试试

**Comment by 4041110** [comment]
好的谢谢
