### ISSUE TITLE
AdguardHome搭配SmartDNS,smartdns需要如何配置 

### ISSUE THREAD

**Issue by dhlsam1987** [garypang13/Actions-OpenWrt-Nginx#7]
大佬，固件使用后，adguardhome好想配置文件都配置好了dns和去广告条目，如何搭配smartdns设置，启用第一第二DNS服务器后还需要设置什么么

**Comment by garypang13** [comment]
smartdns也配置好了的,不用启动第二DNS服务器,把TCP服务器和域名预加载勾上就好了.

**Comment by dhlsam1987** [comment]
设置成功了，这个根it奶爸那个视频原理一样，smartdns是adguard上游 然后adguard是dnsmasq上游

**Comment by garypang13** [comment]
是的哈.

**Comment by dhlsam1987** [comment]
大佬，非常好的固件，可以加上l大最新的airplay2和PCHiFi 数字转盘遥控还有新的cifs-mount这个插件么，这样软路由插了usb声卡就可以当播放器了，cifs-mount这个就不用老的smb 就可以挂载nas上的盘做下载盘了，我自己修改了config文件，可是每次云编译都编译失败
CONFIG_PACKAGE_luci-app-cifs-mount=y
CONFIG_PACKAGE_luci-app-music-remote-center=y
CONFIG_PACKAGE_luci-app-airplay2=y
airplay2需要的kernel 
CONFIG_PACKAGE_kmod-sound-core=y
CONFIG_PACKAGE_kmod-usb-audio=y

**Comment by garypang13** [comment]
已加入cifs-mount和music-remote-center
airplay2和music-remote-center功能有重复么,一直没在用苹果设备,不太熟悉.

**Comment by sarsmark-git** [comment]
openlash能加入吗，似乎不错的样子

**Comment by sarsmark-git** [comment]
还有AdguardHome是默认启用的，smartdns又没有，这是故意的吗？能否都默认不启用。

**Comment by garypang13** [comment]
更新到今天编译的版本,smartdns就默认开启了,
现在的这两个翻墙工具完全够用了,openlash相对更复杂,属于比较折腾的.后续我看需要的人多不多再看是否加入.

**Comment by garypang13** [comment]
添加了PCHiFi 但是开启不了,也不报任何错误,你刷最新版测试下看怎么使用,不行就只能先去掉 @dhlsam1987

**Comment by dhlsam1987** [comment]
airplay2和music-remote-center功能是不同的 ，一个是接收，一个是媒体播放服务器

**Comment by garypang13** [comment]
airplay2需求太小众了 暂时先不加了.

**Comment by dhlsam1987** [comment]
好嘞 感谢

**Comment by imjunfeng** [comment]
airplay2加进去呗，挺好用的，老的音响接个小路由插个声卡，苹果设备就能投送无损音频了

**Comment by garypang13** [comment]
> airplay2加进去呗，挺好用的，老的音响接个小路由插个声卡，苹果设备就能投送无损音频了

airplay2 暂时以独立插件的形式提供,可自行安装
