### ISSUE TITLE
软件包

### ISSUE THREAD

**Issue by 4041110** [garypang13/Actions-OpenWrt-Nginx#70]
更新到最新代码了，软件包里面的可用是空白的，请问是不是需要自己去下载安装包安装才可以呢

**Comment by garypang13** [comment]
软件包里 点击更新列表,
另外你那边能打开
https://openwrt.supes.top

**Comment by 4041110** [comment]
> 不需要自己去下载
> 一部分里点击更新列表，可以
> 看到所有可用的插件。
> 如果很多第三方插件找到的话，确定是否能打开
> https://openwrt.supes.top
> 这个网址
好的谢谢
https://openwrt.supes.top/打不开

**Comment by garypang13** [comment]
忘了加端口了, 是https://openwrt.supes.top:888
