### ISSUE TITLE
在虚拟机中运行时提示错误

### ISSUE THREAD

**Issue by luotao21** [garypang13/Actions-OpenWrt-Nginx#72]
/bin/ash: /etc/profile.d/sysinfo.sh: line 30: syntax error: unexpected

**Comment by garypang13** [comment]
奇怪,是直接用的我编译好的固件吗

**Comment by 4041110** [comment]
用编译好的和自己编译的都会。还有内置AdguardHome搭配SmartDNS综合优化方案，好像没看到这两个，是需要自己安装吗

**Comment by garypang13** [comment]
是的,需要自己安装,安装好后会默认配置好,

**Comment by 4041110** [comment]
/bin/ash: /etc/profile.d/sysinfo.sh: line 30: syntax error: unexpected
修复了麻烦提醒下，才好更新，谢谢

**Comment by garypang13** [comment]
> /bin/ash: /etc/profile.d/sysinfo.sh: line 30: syntax error: unexpected
> 修复了麻烦提醒下，才好更新，谢谢

是终端SSH登录后报错吗,能上个截图么,因为我这边无法重现这个错误.

**Comment by 4041110** [comment]
![IMG_3340](https://user-images.githubusercontent.com/60958209/84616926-f778bd00-aeff-11ea-9e45-28aa5ddebaf3.PNG)

**Comment by garypang13** [comment]
已修复 @4041110 @luotao21

**Comment by 4041110** [comment]
好的谢谢
