### ISSUE TITLE
docker和dockerman无法安装 报kernel不兼容

### ISSUE THREAD

**Issue by song2002102** [garypang13/Actions-OpenWrt-Nginx#73]
docker和dockerman无法安装 报kernel不兼容 请求帮助 谢谢

**Comment by song2002102** [comment]
Docker Engine is used by millions enables containerized applications to run anywhere consistently on any infrastructure.

已安装的软件包 kernel 版本不兼容，要求 5.4.45-1-e3aa7d0c… 而 5.4.45-1-ab3a9556… 已安装。

**Comment by garypang13** [comment]
无视就好了,点击安装是能安装成功的 .

**Comment by song2002102** [comment]
强制安装后 dockerman的概览中 docker的版本、api  所在目录等信息 无内容 好像 docker maemon 没启动

**Comment by garypang13** [comment]
> 强制安装后 dockerman的概览中 docker的版本、api 所在目录等信息 无内容 好像 docker maemon 没启动

确实无法启动,我先看看有没解决方案,不行就另出一版带docker的版本.

**Comment by song2002102** [comment]
谢谢，大佬

**Comment by garypang13** [comment]
已经修复.
