### ISSUE TITLE
samba编译不成功

### ISSUE THREAD

**Issue by klxyy** [garypang13/Actions-OpenWrt-Nginx#74]
开启samba编译出错，怎么处理啊？

**Comment by garypang13** [comment]
samba和samba4不要同时开启,建议使用samba4,

**Comment by klxyy** [comment]
> samba和samba4不要同时开启,建议使用samba4,

大佬这么晚还没睡？只开启了SAMBA，是不是因为开启了AUTOSAMBA的原因？
