### ISSUE TITLE
 Default PPPOE Setting  云编卡这了

### ISSUE THREAD

**Issue by Tiexcn** [garypang13/Actions-OpenWrt-Nginx#8]
Default PPPOE Setting
##[error]Process completed with exit code 2.
Run sed -i '$i uci set network.wan.username=***' openwrt/package/*/*/default-settings/files/zzz-default-settings
sed: can't read openwrt/package/lean/default-settings/files/zzz-default-settings: No such file or directory
##[error]Process completed with exit code 2.

不添加 PPPOE_USERNAME, PPPOE_PASSWD  即可正常完成任务。反馈看看吧。可能是我自己的问题。

**Comment by garypang13** [comment]
感谢反馈,已修复.

**Comment by Tiexcn** [comment]
大佬 ，你真效率。
