### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by CORE2021** [garypang13/Actions-OpenWrt-Nginx#80]
安装passwall提示版本错误，但能打开界面 添加节点报告错误但实际能添加；dnscrypt-proxy2不会自动安装依赖项libustream-ssl还需要手动安装

**Comment by garypang13** [comment]
不建议再使用passwall了,作者都删库弃更了,本身这个插件就有不少bug,以后bug会越来越多,早晚要换的,
dnscrypt-proxy2是官方编译的,官方并没有要求libustream-ssl依赖,
