### ISSUE TITLE
luci-app-cifs-mount 无法使用

### ISSUE THREAD

**Issue by goofysun** [garypang13/Actions-OpenWrt-Nginx#83]
luci-app-cifs-mount 在 这个固件下应该不兼容，无法挂载，并且尝试挂载重启 就无法启动了，一直循环重启

**Comment by garypang13** [comment]
我试了luci-app-cifs-mount 并没有问题, 目前我测试有问题的只有luci-app-ksmbd, 换用luci-app-samba4或luci-app-samba即可.

**Comment by garypang13** [comment]
确实有问题,现已修复,刷最新固件即可.
