### ISSUE TITLE
06/26 2020 phicomm_k2p无线有问题

### ISSUE THREAD

**Issue by fm571** [garypang13/Actions-OpenWrt-Nginx#84]
最大传输功率只能设置10dbm，更改国家到美国或者澳大利亚都一样只能10dbm

**Comment by fm571** [comment]
![11](https://user-images.githubusercontent.com/64844177/85810267-16dbd980-b78d-11ea-80c2-9e8ee79515f4.jpg)

**Comment by garypang13** [comment]
已更换为闭源无线驱动.
