### ISSUE TITLE
反映2个问题

### ISSUE THREAD

**Issue by lx521603** [garypang13/Actions-OpenWrt-Nginx#97]
我不知道是我自己的问题，还是官方的出问题了。

提示miniupnp出错，编译不成功。 去掉upnp后，编译成功。

前几天smartdns莫名其妙挂掉，到今天也启动不成功，大概5天了。我换之前正常的任何插件都不能把smartdns启动起来。

我的环境是虚拟机。

**Comment by garypang13** [comment]
miniupnp是官方源码的问题,官方已经修复了.
smartdns启动不起来有可能是端口冲突了.
