### ISSUE TITLE
更新smartdns

### ISSUE THREAD

**Issue by lx521603** [garypang13/Actions-OpenWrt-Nginx#99]
.config里选smartdns，编译进固件里面的，不能运行。
软件包里，卸载smartdns。
github的smartdns发布页下载最新的smartdns.1.2020.05.04-0005.x86_64-openwrt-all.ipk安装后，问题解决。

luci-app-smartdns这个没问题，我没动。

**Comment by garypang13** [comment]
smartdns没问题的,smartdns的来源是官方packages,我都是用的那个.

**Comment by lx521603** [comment]
> smartdns没问题的,smartdns的来源是官方packages,我都是用的那个.

刚起来发现没网。看了下smartdns ,ssr+都挂了，其它的我没注意，启动项里面，把所有手动点了一遍启动，然后所有都恢复正常了。 

在重启那里点重启，结果发现不是真正的重启，因为状态那里还是显示运行了好久的时间。

**Comment by lx521603** [comment]
没问题了
